 version=0.1
 [default.deploy.parameters]
 stack_name = "ts-graphql-hw-with-sam"
 s3_bucket = "my-source-bucket"
 s3_prefix = "my-s3-prefix"
 region = "ap-southeast-2"
 confirm_changeset = true
 capabilities = "CAPABILITY_IAM"
 tags = "project=\"aws-lambda-template\" stage=\"test\""
