# For further info on SAM template, go to: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-specification-template-anatomy.html
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  ts-simple-api-proxy-with-sam

  Sample SAM Template for ts-simple-api-proxy

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 120

Resources:
  HelloWorldGqFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      Handler: ./dist/index.grapqlHandler # name of the handler function in src/handler.js
      Runtime: nodejs14.x
      Events:
        HelloWorldGq:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /graphql
            Method: get
        HelloWorldGqPost:
          Type: Api
          Properties:
            Path: /graphql
            Method: post

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HelloWorldGqApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World GraphQL function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  HelloWorldGqFunction:
    Description: "Hello World GraphQL Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldGqFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World GraphQL function"
    Value: !GetAtt HelloWorldFunctionRole.Arn
